# Generated by Django 2.0.8 on 2019-11-07 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photohunt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disabled', 'disabled')], default='pending', max_length=200)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(max_length=200, upload_to=photohunt.models.Image.image_name)),
            ],
        ),
        migrations.CreateModel(
            name='Parasite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('nematode', 'nematode'), ('cestode', 'cestode'), ('trematode', 'trematode'), ('protozoa', 'protozoa')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='parasite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photohunt.Parasite'),
        ),
        migrations.AddField(
            model_name='image',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
