# Generated by Django 2.0.8 on 2019-11-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0002_auto_20191107_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
