# Generated by Django 2.0.8 on 2019-11-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0003_auto_20191113_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('tagset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='photohunt.ImageTagSet')),
            ],
        ),
    ]
