# Generated by Django 2.0.8 on 2019-11-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetagset',
            name='title',
            field=models.TextField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='answer',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='question',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='imagetagset',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
