# Generated by Django 2.0.8 on 2019-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0005_auto_20191113_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('questions', models.ManyToManyField(to='photohunt.Question')),
            ],
        ),
    ]
