# Generated by Django 2.0.8 on 2019-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0006_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tagset',
        ),
        migrations.AddField(
            model_name='question',
            name='tagsets',
            field=models.ManyToManyField(to='photohunt.ImageTagSet'),
        ),
    ]
