# Generated by Django 2.0.8 on 2019-11-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0007_auto_20191122_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tagset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='photohunt.ImageTagSet'),
            preserve_default=False,
        ),
    ]
