# Generated by Django 2.0.8 on 2019-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0009_remove_question_tagsets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='questions',
        ),
        migrations.AddField(
            model_name='session',
            name='tagsets',
            field=models.ManyToManyField(to='photohunt.ImageTagSet'),
        ),
    ]
