# Generated by Django 2.0.8 on 2019-12-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0010_auto_20191203_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='photohunt.Discipline'),
            preserve_default=False,
        ),
    ]
