# Generated by Django 2.0.8 on 2019-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0012_auto_20191209_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disabled', 'disabled')], default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='target',
            field=models.CharField(default='Some sample program', max_length=200),
            preserve_default=False,
        ),
    ]
