# Generated by Django 2.0.8 on 2020-03-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photohunt', '0014_photohuntplayrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photohuntplayrecord',
            old_name='section',
            new_name='session',
        ),
    ]
