# Generated by Django 2.0.8 on 2018-11-12 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import microscope.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microscope', '0002_auto_20181003_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disabled', 'disabled')], default='pending', max_length=200)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(max_length=200, upload_to=microscope.models.ArtifactImage.image_name)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='microscope.Artifact')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='parasitestage',
            name='stage',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='artifact',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='microscope.ArtifactType'),
        ),
    ]
