# Generated by Django 2.0.8 on 2018-11-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0005_auto_20181112_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='program',
        ),
        migrations.RemoveField(
            model_name='session',
            name='upload_by',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
