# Generated by Django 2.0.8 on 2018-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0007_auto_20181116_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='microscopeitem',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
