# Generated by Django 2.0.8 on 2018-11-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0008_microscopeitem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microscopeitem',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
