# Generated by Django 2.0.8 on 2018-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0009_auto_20181116_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='microscopesection',
            name='desc',
            field=models.TextField(default='Try to find eggs as much as possible'),
            preserve_default=False,
        ),
    ]
