# Generated by Django 2.0.8 on 2018-11-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0010_microscopesection_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microscope.Artifact')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_comps', to='microscope.MicroscopeSection')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microscope.ArtifactImage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='microscope.MicroscopeSection')),
            ],
        ),
        migrations.CreateModel(
            name='ParasiteComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('parasite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microscope.Parasite')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parasite_comps', to='microscope.MicroscopeSection')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microscope.ParasiteStage')),
            ],
        ),
        migrations.CreateModel(
            name='ParasiteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microscope.ParasiteImage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parasites', to='microscope.MicroscopeSection')),
            ],
        ),
        migrations.RemoveField(
            model_name='microscopeitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='microscopeitem',
            name='section',
        ),
        migrations.DeleteModel(
            name='MicroscopeItem',
        ),
    ]
