# Generated by Django 2.0.8 on 2018-11-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0011_auto_20181116_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactitem',
            name='section',
        ),
        migrations.RemoveField(
            model_name='parasiteitem',
            name='section',
        ),
        migrations.AddField(
            model_name='artifactitem',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='microscope.ArtifactComponent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parasiteitem',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parasites', to='microscope.ParasiteComponent'),
            preserve_default=False,
        ),
    ]
