# Generated by Django 2.0.8 on 2018-11-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0012_auto_20181118_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactcomponent',
            name='oscillate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artifactcomponent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_components', to='microscope.MicroscopeSection'),
        ),
        migrations.AlterField(
            model_name='parasitecomponent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parasite_components', to='microscope.MicroscopeSection'),
        ),
    ]
