# Generated by Django 2.0.8 on 2018-11-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0013_auto_20181118_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactitem',
            name='component',
        ),
        migrations.RemoveField(
            model_name='artifactitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='parasiteitem',
            name='component',
        ),
        migrations.RemoveField(
            model_name='parasiteitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='ArtifactItem',
        ),
        migrations.DeleteModel(
            name='ParasiteItem',
        ),
    ]
