# Generated by Django 2.0.8 on 2018-11-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0014_auto_20181118_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactcomponent',
            name='resizable',
            field=models.BooleanField(default=False),
        ),
    ]
