# Generated by Django 2.0.8 on 2018-12-11 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('microscope', '0016_artifactcomponent_floating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParasitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parasite_pages', to='wagtailcore.Page')),
                ('parasite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parasite_pages', to='microscope.Parasite')),
            ],
        ),
    ]
