# Generated by Django 2.0.8 on 2018-11-16 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microscope', '0006_auto_20181112_1528'),
        ('main', '0002_auto_20181113_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroscopeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='microscope_items', to='microscope.ParasiteImage')),
            ],
        ),
        migrations.CreateModel(
            name='MicroscopeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microscope_sections', to='main.Session')),
            ],
        ),
        migrations.AddField(
            model_name='microscopeitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.MicroscopeSection'),
        ),
    ]
